import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#006398",
        "surface-container-low": "#f5f3f3",
        "on-secondary-fixed": "#001e2d",
        tertiary: "#465a73",
        "surface-dim": "#dbdad9",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#93ccff",
        "inverse-surface": "#303031",
        "secondary-fixed": "#c6e7ff",
        background: "#fbf9f8",
        "on-primary-container": "#f3f7ff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e9e8e7",
        secondary: "#00658d",
        "primary-fixed": "#cde5ff",
        "on-primary-fixed": "#001d32",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fbf9f8",
        primary: "#005d8f",
        "on-tertiary-container": "#f4f7ff",
        "tertiary-fixed-dim": "#b3c8e5",
        "surface-variant": "#e4e2e2",
        "on-primary-fixed-variant": "#004b74",
        "tertiary-container": "#5e738d",
        "secondary-fixed-dim": "#82cfff",
        "on-secondary-fixed-variant": "#004c6b",
        "on-error": "#ffffff",
        "outline-variant": "#bfc7d1",
        "on-primary": "#ffffff",
        "on-surface": "#1b1c1c",
        "on-secondary-container": "#004d6c",
        "on-surface-variant": "#404850",
        "secondary-container": "#48c1ff",
        "surface-container": "#efeded",
        "primary-fixed-dim": "#93ccff",
        "primary-container": "#0077b5",
        "error-container": "#ffdad6",
        outline: "#707881",
        "on-tertiary-fixed-variant": "#344860",
        "surface-container-highest": "#e4e2e2",
        "tertiary-fixed": "#d1e4ff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f2f0f0",
        surface: "#fbf9f8",
        "on-tertiary-fixed": "#051d33",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-sm": "4px",
        "gutter-mobile": "12px",
        "margin-mobile": "16px",
        "stack-md": "12px",
        "container-padding": "16px",
        "stack-lg": "24px",
        base: "8px",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      boxShadow: {
        "resume": "0px 2px 8px rgba(0, 0, 0, 0.05)",
        "topbar": "0px 2px 8px rgba(0, 0, 0, 0.05)",
        "bottombar": "0px -2px 8px rgba(0, 0, 0, 0.05)",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "slide-up": "slideUp 0.3s ease-out",
        "fade-in": "fadeIn 0.3s ease-out",
      },
      keyframes: {
        slideUp: {
          "0%": { transform: "translateY(16px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
